### ISSUE TITLE
newline characters in Fasta header cause mismatch

### ISSUE THREAD

**Issue by wowwish** [signalbash/how_are_we_stranded_here#7]
I just encountered a bug where the FASTA header with newline does not match with the BED file ID. I guess the newline needs to be stripped from the header.

**Comment by boyangzhao** [comment]
yes I have the same problem - I don't if it's the newline or what, but bed id and the fasta header doesn't match, when it should.

**Comment by signalbash** [comment]
https://github.com/signalbash/how_are_we_stranded_here/commit/0fedf9245c3bbbcdf670e2b374196ca5d40cab25
